version: 2

builds:
- main: ./cmd/crand
  binary: dp-crand
  env:
  - CGO_ENABLED=0
  goos:
  - linux

archives:
- format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch | tolower }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  draft: true
  replace_existing_draft: true
  extra_files:
  - glob: cdi.tar.gz

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
