apiVersion: v1
kind: Pod
metadata:
  name: busybox-crand
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - infinity
    resources:
      requests:
        github.com.ihcsim/crand: 2
      limits:
        github.com.ihcsim/crand: 2
