apiVersion: v1
kind: Pod
metadata:
  name: busybox-kvm
spec:
  containers:
  - image: busybox
    name: busybox
    command:
    - sleep
    - infinity
    resources:
      requests:
        github.com.ihcsim/kvm: 1
      limits:
        github.com.ihcsim/kvm: 1
