name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58
    - run: make tidy
    - run: make lint
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: ${{ github.workspace }}

  test:
    needs: prebuild
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build
    - run: make test
